# Copyright IBM Corp. 2026
# SPDX-License-Identifier: MIT

default_install_hook_types:
  - pre-commit
  - commit-msg

repos:
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: 91ab4bf57e58b32adf1a122681f6ebe164d081c8 # v4.4.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: []
