# Copyright IBM Corp. 2026
# SPDX-License-Identifier: MIT

default_install_hook_types:
  - pre-commit
  - commit-msg

repos:
  - repo: https://github.com/golangci/golangci-lint
    rev: v2.13.2
    hooks:
      - id: golangci-lint
      - id: golangci-lint-fmt
  - repo: https://github.com/hashicorp/copywrite
    rev: v0.25.3
    hooks:
      - id: add-headers
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: 91ab4bf57e58b32adf1a122681f6ebe164d081c8 # v4.4.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: []
