// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: pkg/proto/access.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AccessData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CreatedAt     string                 `protobuf:"bytes,1,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Records       []*AccessRecord        `protobuf:"bytes,3,rep,name=records,proto3" json:"records,omitempty"`
	Stats         *AccessStats           `protobuf:"bytes,4,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessData) Reset() {
	*x = AccessData{}
	mi := &file_pkg_proto_access_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessData) ProtoMessage() {}

func (x *AccessData) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_access_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessData.ProtoReflect.Descriptor instead.
func (*AccessData) Descriptor() ([]byte, []int) {
	return file_pkg_proto_access_proto_rawDescGZIP(), []int{0}
}

func (x *AccessData) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *AccessData) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *AccessData) GetRecords() []*AccessRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *AccessData) GetStats() *AccessStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

type AccessRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NamespacePath string                 `protobuf:"bytes,1,opt,name=namespace_path,json=namespacePath,proto3" json:"namespace_path,omitempty"`
	MountPath     string                 `protobuf:"bytes,3,opt,name=mount_path,json=mountPath,proto3" json:"mount_path,omitempty"`
	MountAccessor string                 `protobuf:"bytes,4,opt,name=mount_accessor,json=mountAccessor,proto3" json:"mount_accessor,omitempty"`
	SecretPath    string                 `protobuf:"bytes,5,opt,name=secret_path,json=secretPath,proto3" json:"secret_path,omitempty"`
	LastAccessed  string                 `protobuf:"bytes,6,opt,name=last_accessed,json=lastAccessed,proto3" json:"last_accessed,omitempty"`
	AccessType    string                 `protobuf:"bytes,7,opt,name=access_type,json=accessType,proto3" json:"access_type,omitempty"`
	AccessCount   int32                  `protobuf:"varint,8,opt,name=access_count,json=accessCount,proto3" json:"access_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessRecord) Reset() {
	*x = AccessRecord{}
	mi := &file_pkg_proto_access_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessRecord) ProtoMessage() {}

func (x *AccessRecord) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_access_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessRecord.ProtoReflect.Descriptor instead.
func (*AccessRecord) Descriptor() ([]byte, []int) {
	return file_pkg_proto_access_proto_rawDescGZIP(), []int{1}
}

func (x *AccessRecord) GetNamespacePath() string {
	if x != nil {
		return x.NamespacePath
	}
	return ""
}

func (x *AccessRecord) GetMountPath() string {
	if x != nil {
		return x.MountPath
	}
	return ""
}

func (x *AccessRecord) GetMountAccessor() string {
	if x != nil {
		return x.MountAccessor
	}
	return ""
}

func (x *AccessRecord) GetSecretPath() string {
	if x != nil {
		return x.SecretPath
	}
	return ""
}

func (x *AccessRecord) GetLastAccessed() string {
	if x != nil {
		return x.LastAccessed
	}
	return ""
}

func (x *AccessRecord) GetAccessType() string {
	if x != nil {
		return x.AccessType
	}
	return ""
}

func (x *AccessRecord) GetAccessCount() int32 {
	if x != nil {
		return x.AccessCount
	}
	return 0
}

type AccessStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalRecords  int32                  `protobuf:"varint,1,opt,name=total_records,json=totalRecords,proto3" json:"total_records,omitempty"`
	ReadCount     int32                  `protobuf:"varint,2,opt,name=read_count,json=readCount,proto3" json:"read_count,omitempty"`
	WriteCount    int32                  `protobuf:"varint,3,opt,name=write_count,json=writeCount,proto3" json:"write_count,omitempty"`
	DeleteCount   int32                  `protobuf:"varint,4,opt,name=delete_count,json=deleteCount,proto3" json:"delete_count,omitempty"`
	UniqueSecrets int32                  `protobuf:"varint,5,opt,name=unique_secrets,json=uniqueSecrets,proto3" json:"unique_secrets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessStats) Reset() {
	*x = AccessStats{}
	mi := &file_pkg_proto_access_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessStats) ProtoMessage() {}

func (x *AccessStats) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_access_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessStats.ProtoReflect.Descriptor instead.
func (*AccessStats) Descriptor() ([]byte, []int) {
	return file_pkg_proto_access_proto_rawDescGZIP(), []int{2}
}

func (x *AccessStats) GetTotalRecords() int32 {
	if x != nil {
		return x.TotalRecords
	}
	return 0
}

func (x *AccessStats) GetReadCount() int32 {
	if x != nil {
		return x.ReadCount
	}
	return 0
}

func (x *AccessStats) GetWriteCount() int32 {
	if x != nil {
		return x.WriteCount
	}
	return 0
}

func (x *AccessStats) GetDeleteCount() int32 {
	if x != nil {
		return x.DeleteCount
	}
	return 0
}

func (x *AccessStats) GetUniqueSecrets() int32 {
	if x != nil {
		return x.UniqueSecrets
	}
	return 0
}

var File_pkg_proto_access_proto protoreflect.FileDescriptor

const file_pkg_proto_access_proto_rawDesc = "" +
	"\n" +
	"\x16pkg/proto/access.proto\x12\x05proto\"\x9c\x01\n" +
	"\n" +
	"AccessData\x12\x1d\n" +
	"\n" +
	"created_at\x18\x01 \x01(\tR\tcreatedAt\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12-\n" +
	"\arecords\x18\x03 \x03(\v2\x13.proto.AccessRecordR\arecords\x12(\n" +
	"\x05stats\x18\x04 \x01(\v2\x12.proto.AccessStatsR\x05stats\"\x85\x02\n" +
	"\fAccessRecord\x12%\n" +
	"\x0enamespace_path\x18\x01 \x01(\tR\rnamespacePath\x12\x1d\n" +
	"\n" +
	"mount_path\x18\x03 \x01(\tR\tmountPath\x12%\n" +
	"\x0emount_accessor\x18\x04 \x01(\tR\rmountAccessor\x12\x1f\n" +
	"\vsecret_path\x18\x05 \x01(\tR\n" +
	"secretPath\x12#\n" +
	"\rlast_accessed\x18\x06 \x01(\tR\flastAccessed\x12\x1f\n" +
	"\vaccess_type\x18\a \x01(\tR\n" +
	"accessType\x12!\n" +
	"\faccess_count\x18\b \x01(\x05R\vaccessCount\"\xbc\x01\n" +
	"\vAccessStats\x12#\n" +
	"\rtotal_records\x18\x01 \x01(\x05R\ftotalRecords\x12\x1d\n" +
	"\n" +
	"read_count\x18\x02 \x01(\x05R\treadCount\x12\x1f\n" +
	"\vwrite_count\x18\x03 \x01(\x05R\n" +
	"writeCount\x12!\n" +
	"\fdelete_count\x18\x04 \x01(\x05R\vdeleteCount\x12%\n" +
	"\x0eunique_secrets\x18\x05 \x01(\x05R\runiqueSecretsB7Z5github.com/gsantos-hc/vault-secrets-cleanup/pkg/protob\x06proto3"

var (
	file_pkg_proto_access_proto_rawDescOnce sync.Once
	file_pkg_proto_access_proto_rawDescData []byte
)

func file_pkg_proto_access_proto_rawDescGZIP() []byte {
	file_pkg_proto_access_proto_rawDescOnce.Do(func() {
		file_pkg_proto_access_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_access_proto_rawDesc), len(file_pkg_proto_access_proto_rawDesc)))
	})
	return file_pkg_proto_access_proto_rawDescData
}

var file_pkg_proto_access_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pkg_proto_access_proto_goTypes = []any{
	(*AccessData)(nil),   // 0: proto.AccessData
	(*AccessRecord)(nil), // 1: proto.AccessRecord
	(*AccessStats)(nil),  // 2: proto.AccessStats
}
var file_pkg_proto_access_proto_depIdxs = []int32{
	1, // 0: proto.AccessData.records:type_name -> proto.AccessRecord
	2, // 1: proto.AccessData.stats:type_name -> proto.AccessStats
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_proto_access_proto_init() }
func file_pkg_proto_access_proto_init() {
	if File_pkg_proto_access_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_access_proto_rawDesc), len(file_pkg_proto_access_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_proto_access_proto_goTypes,
		DependencyIndexes: file_pkg_proto_access_proto_depIdxs,
		MessageInfos:      file_pkg_proto_access_proto_msgTypes,
	}.Build()
	File_pkg_proto_access_proto = out.File
	file_pkg_proto_access_proto_goTypes = nil
	file_pkg_proto_access_proto_depIdxs = nil
}
