// Copyright IBM Corp. 2026
// SPDX-License-Identifier: MIT

syntax = "proto3";

package proto;

option go_package = "github.com/gsantos-hc/vault-secrets-cleanup/pkg/proto";

message AccessData {
  string created_at = 1;
  string source = 2;
  repeated AccessRecord records = 3;
  AccessStats stats = 4;
}

message AccessRecord {
  string namespace_path = 1;
  string mount_path = 3;
  string mount_accessor = 4;
  string secret_path = 5;
  string last_accessed = 6;
  string access_type = 7;
  int32 access_count = 8;
}

message AccessStats {
  int32 total_records = 1;
  int32 read_count = 2;
  int32 write_count = 3;
  int32 delete_count = 4;
  int32 unique_secrets = 5;
}
