syntax = "proto3";

package proto;

option go_package = "github.com/gsantos-hc/vault-secrets-cleanup/pkg/proto";

message Inventory {
  string created_at = 1;
  string vault_address = 2;
  repeated Namespace namespaces = 3;
  InventoryStats stats = 4;
}

message Namespace {
  string path = 1;
  string id = 2;
  repeated Mount mounts = 3;
}

message Mount {
  string path = 1;
  string accessor = 2;
  string type = 3;
  int32 version = 4;
  repeated Secret secrets = 5;
}

message Secret {
  string path = 1;
  string discovered_at = 2;
}

message InventoryStats {
  int32 namespace_count = 1;
  int32 mount_count = 2;
  int32 secret_count = 3;
  int32 kv_v1_count = 4;
  int32 kv_v2_count = 5;
}
