// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: pkg/proto/inventory.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Inventory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CreatedAt     string                 `protobuf:"bytes,1,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	VaultAddress  string                 `protobuf:"bytes,2,opt,name=vault_address,json=vaultAddress,proto3" json:"vault_address,omitempty"`
	Namespaces    []*Namespace           `protobuf:"bytes,3,rep,name=namespaces,proto3" json:"namespaces,omitempty"`
	Stats         *InventoryStats        `protobuf:"bytes,4,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Inventory) Reset() {
	*x = Inventory{}
	mi := &file_pkg_proto_inventory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Inventory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Inventory) ProtoMessage() {}

func (x *Inventory) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_inventory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Inventory.ProtoReflect.Descriptor instead.
func (*Inventory) Descriptor() ([]byte, []int) {
	return file_pkg_proto_inventory_proto_rawDescGZIP(), []int{0}
}

func (x *Inventory) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Inventory) GetVaultAddress() string {
	if x != nil {
		return x.VaultAddress
	}
	return ""
}

func (x *Inventory) GetNamespaces() []*Namespace {
	if x != nil {
		return x.Namespaces
	}
	return nil
}

func (x *Inventory) GetStats() *InventoryStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

type Namespace struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Mounts        []*Mount               `protobuf:"bytes,3,rep,name=mounts,proto3" json:"mounts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Namespace) Reset() {
	*x = Namespace{}
	mi := &file_pkg_proto_inventory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Namespace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Namespace) ProtoMessage() {}

func (x *Namespace) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_inventory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Namespace.ProtoReflect.Descriptor instead.
func (*Namespace) Descriptor() ([]byte, []int) {
	return file_pkg_proto_inventory_proto_rawDescGZIP(), []int{1}
}

func (x *Namespace) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Namespace) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Namespace) GetMounts() []*Mount {
	if x != nil {
		return x.Mounts
	}
	return nil
}

type Mount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Accessor      string                 `protobuf:"bytes,2,opt,name=accessor,proto3" json:"accessor,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Version       int32                  `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	Secrets       []*Secret              `protobuf:"bytes,5,rep,name=secrets,proto3" json:"secrets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Mount) Reset() {
	*x = Mount{}
	mi := &file_pkg_proto_inventory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mount) ProtoMessage() {}

func (x *Mount) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_inventory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mount.ProtoReflect.Descriptor instead.
func (*Mount) Descriptor() ([]byte, []int) {
	return file_pkg_proto_inventory_proto_rawDescGZIP(), []int{2}
}

func (x *Mount) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Mount) GetAccessor() string {
	if x != nil {
		return x.Accessor
	}
	return ""
}

func (x *Mount) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Mount) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Mount) GetSecrets() []*Secret {
	if x != nil {
		return x.Secrets
	}
	return nil
}

type Secret struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	DiscoveredAt  string                 `protobuf:"bytes,2,opt,name=discovered_at,json=discoveredAt,proto3" json:"discovered_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Secret) Reset() {
	*x = Secret{}
	mi := &file_pkg_proto_inventory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Secret) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Secret) ProtoMessage() {}

func (x *Secret) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_inventory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Secret.ProtoReflect.Descriptor instead.
func (*Secret) Descriptor() ([]byte, []int) {
	return file_pkg_proto_inventory_proto_rawDescGZIP(), []int{3}
}

func (x *Secret) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Secret) GetDiscoveredAt() string {
	if x != nil {
		return x.DiscoveredAt
	}
	return ""
}

type InventoryStats struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NamespaceCount int32                  `protobuf:"varint,1,opt,name=namespace_count,json=namespaceCount,proto3" json:"namespace_count,omitempty"`
	MountCount     int32                  `protobuf:"varint,2,opt,name=mount_count,json=mountCount,proto3" json:"mount_count,omitempty"`
	SecretCount    int32                  `protobuf:"varint,3,opt,name=secret_count,json=secretCount,proto3" json:"secret_count,omitempty"`
	KvV1Count      int32                  `protobuf:"varint,4,opt,name=kv_v1_count,json=kvV1Count,proto3" json:"kv_v1_count,omitempty"`
	KvV2Count      int32                  `protobuf:"varint,5,opt,name=kv_v2_count,json=kvV2Count,proto3" json:"kv_v2_count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InventoryStats) Reset() {
	*x = InventoryStats{}
	mi := &file_pkg_proto_inventory_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventoryStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryStats) ProtoMessage() {}

func (x *InventoryStats) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_inventory_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryStats.ProtoReflect.Descriptor instead.
func (*InventoryStats) Descriptor() ([]byte, []int) {
	return file_pkg_proto_inventory_proto_rawDescGZIP(), []int{4}
}

func (x *InventoryStats) GetNamespaceCount() int32 {
	if x != nil {
		return x.NamespaceCount
	}
	return 0
}

func (x *InventoryStats) GetMountCount() int32 {
	if x != nil {
		return x.MountCount
	}
	return 0
}

func (x *InventoryStats) GetSecretCount() int32 {
	if x != nil {
		return x.SecretCount
	}
	return 0
}

func (x *InventoryStats) GetKvV1Count() int32 {
	if x != nil {
		return x.KvV1Count
	}
	return 0
}

func (x *InventoryStats) GetKvV2Count() int32 {
	if x != nil {
		return x.KvV2Count
	}
	return 0
}

var File_pkg_proto_inventory_proto protoreflect.FileDescriptor

const file_pkg_proto_inventory_proto_rawDesc = "" +
	"\n" +
	"\x19pkg/proto/inventory.proto\x12\x05proto\"\xae\x01\n" +
	"\tInventory\x12\x1d\n" +
	"\n" +
	"created_at\x18\x01 \x01(\tR\tcreatedAt\x12#\n" +
	"\rvault_address\x18\x02 \x01(\tR\fvaultAddress\x120\n" +
	"\n" +
	"namespaces\x18\x03 \x03(\v2\x10.proto.NamespaceR\n" +
	"namespaces\x12+\n" +
	"\x05stats\x18\x04 \x01(\v2\x15.proto.InventoryStatsR\x05stats\"U\n" +
	"\tNamespace\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12$\n" +
	"\x06mounts\x18\x03 \x03(\v2\f.proto.MountR\x06mounts\"\x8e\x01\n" +
	"\x05Mount\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1a\n" +
	"\baccessor\x18\x02 \x01(\tR\baccessor\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x05R\aversion\x12'\n" +
	"\asecrets\x18\x05 \x03(\v2\r.proto.SecretR\asecrets\"A\n" +
	"\x06Secret\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12#\n" +
	"\rdiscovered_at\x18\x02 \x01(\tR\fdiscoveredAt\"\xbd\x01\n" +
	"\x0eInventoryStats\x12'\n" +
	"\x0fnamespace_count\x18\x01 \x01(\x05R\x0enamespaceCount\x12\x1f\n" +
	"\vmount_count\x18\x02 \x01(\x05R\n" +
	"mountCount\x12!\n" +
	"\fsecret_count\x18\x03 \x01(\x05R\vsecretCount\x12\x1e\n" +
	"\vkv_v1_count\x18\x04 \x01(\x05R\tkvV1Count\x12\x1e\n" +
	"\vkv_v2_count\x18\x05 \x01(\x05R\tkvV2CountB7Z5github.com/gsantos-hc/vault-secrets-cleanup/pkg/protob\x06proto3"

var (
	file_pkg_proto_inventory_proto_rawDescOnce sync.Once
	file_pkg_proto_inventory_proto_rawDescData []byte
)

func file_pkg_proto_inventory_proto_rawDescGZIP() []byte {
	file_pkg_proto_inventory_proto_rawDescOnce.Do(func() {
		file_pkg_proto_inventory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_inventory_proto_rawDesc), len(file_pkg_proto_inventory_proto_rawDesc)))
	})
	return file_pkg_proto_inventory_proto_rawDescData
}

var file_pkg_proto_inventory_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_pkg_proto_inventory_proto_goTypes = []any{
	(*Inventory)(nil),      // 0: proto.Inventory
	(*Namespace)(nil),      // 1: proto.Namespace
	(*Mount)(nil),          // 2: proto.Mount
	(*Secret)(nil),         // 3: proto.Secret
	(*InventoryStats)(nil), // 4: proto.InventoryStats
}
var file_pkg_proto_inventory_proto_depIdxs = []int32{
	1, // 0: proto.Inventory.namespaces:type_name -> proto.Namespace
	4, // 1: proto.Inventory.stats:type_name -> proto.InventoryStats
	2, // 2: proto.Namespace.mounts:type_name -> proto.Mount
	3, // 3: proto.Mount.secrets:type_name -> proto.Secret
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_pkg_proto_inventory_proto_init() }
func file_pkg_proto_inventory_proto_init() {
	if File_pkg_proto_inventory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_inventory_proto_rawDesc), len(file_pkg_proto_inventory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_proto_inventory_proto_goTypes,
		DependencyIndexes: file_pkg_proto_inventory_proto_depIdxs,
		MessageInfos:      file_pkg_proto_inventory_proto_msgTypes,
	}.Build()
	File_pkg_proto_inventory_proto = out.File
	file_pkg_proto_inventory_proto_goTypes = nil
	file_pkg_proto_inventory_proto_depIdxs = nil
}
