// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: pkg/proto/plan.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DeletionPlan represents a plan for deleting stale secrets.
type DeletionPlan struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CreatedAt     string                 `protobuf:"bytes,1,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	InventoryFile string                 `protobuf:"bytes,2,opt,name=inventory_file,json=inventoryFile,proto3" json:"inventory_file,omitempty"`
	AccessFile    string                 `protobuf:"bytes,3,opt,name=access_file,json=accessFile,proto3" json:"access_file,omitempty"`
	Config        *PlanConfig            `protobuf:"bytes,4,opt,name=config,proto3" json:"config,omitempty"`
	Actions       []*SecretAction        `protobuf:"bytes,5,rep,name=actions,proto3" json:"actions,omitempty"`
	Stats         *PlanStats             `protobuf:"bytes,6,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletionPlan) Reset() {
	*x = DeletionPlan{}
	mi := &file_pkg_proto_plan_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletionPlan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletionPlan) ProtoMessage() {}

func (x *DeletionPlan) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_plan_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletionPlan.ProtoReflect.Descriptor instead.
func (*DeletionPlan) Descriptor() ([]byte, []int) {
	return file_pkg_proto_plan_proto_rawDescGZIP(), []int{0}
}

func (x *DeletionPlan) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *DeletionPlan) GetInventoryFile() string {
	if x != nil {
		return x.InventoryFile
	}
	return ""
}

func (x *DeletionPlan) GetAccessFile() string {
	if x != nil {
		return x.AccessFile
	}
	return ""
}

func (x *DeletionPlan) GetConfig() *PlanConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *DeletionPlan) GetActions() []*SecretAction {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *DeletionPlan) GetStats() *PlanStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

// PlanConfig contains the configuration used to generate the plan.
type PlanConfig struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	StalenessPeriod   string                 `protobuf:"bytes,1,opt,name=staleness_period,json=stalenessPeriod,proto3" json:"staleness_period,omitempty"`
	MatchingStrategy  string                 `protobuf:"bytes,2,opt,name=matching_strategy,json=matchingStrategy,proto3" json:"matching_strategy,omitempty"`
	IncludeUnknown    bool                   `protobuf:"varint,3,opt,name=include_unknown,json=includeUnknown,proto3" json:"include_unknown,omitempty"`
	ExclusionPatterns []string               `protobuf:"bytes,4,rep,name=exclusion_patterns,json=exclusionPatterns,proto3" json:"exclusion_patterns,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PlanConfig) Reset() {
	*x = PlanConfig{}
	mi := &file_pkg_proto_plan_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanConfig) ProtoMessage() {}

func (x *PlanConfig) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_plan_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanConfig.ProtoReflect.Descriptor instead.
func (*PlanConfig) Descriptor() ([]byte, []int) {
	return file_pkg_proto_plan_proto_rawDescGZIP(), []int{1}
}

func (x *PlanConfig) GetStalenessPeriod() string {
	if x != nil {
		return x.StalenessPeriod
	}
	return ""
}

func (x *PlanConfig) GetMatchingStrategy() string {
	if x != nil {
		return x.MatchingStrategy
	}
	return ""
}

func (x *PlanConfig) GetIncludeUnknown() bool {
	if x != nil {
		return x.IncludeUnknown
	}
	return false
}

func (x *PlanConfig) GetExclusionPatterns() []string {
	if x != nil {
		return x.ExclusionPatterns
	}
	return nil
}

// SecretAction represents an action to take on a secret.
type SecretAction struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NamespacePath   string                 `protobuf:"bytes,1,opt,name=namespace_path,json=namespacePath,proto3" json:"namespace_path,omitempty"`
	MountPath       string                 `protobuf:"bytes,3,opt,name=mount_path,json=mountPath,proto3" json:"mount_path,omitempty"`
	MountAccessor   string                 `protobuf:"bytes,4,opt,name=mount_accessor,json=mountAccessor,proto3" json:"mount_accessor,omitempty"`
	SecretPath      string                 `protobuf:"bytes,5,opt,name=secret_path,json=secretPath,proto3" json:"secret_path,omitempty"`
	Category        string                 `protobuf:"bytes,6,opt,name=category,proto3" json:"category,omitempty"`
	Reason          string                 `protobuf:"bytes,7,opt,name=reason,proto3" json:"reason,omitempty"`
	LastAccessed    string                 `protobuf:"bytes,8,opt,name=last_accessed,json=lastAccessed,proto3" json:"last_accessed,omitempty"`
	DaysSinceAccess int32                  `protobuf:"varint,9,opt,name=days_since_access,json=daysSinceAccess,proto3" json:"days_since_access,omitempty"`
	Status          string                 `protobuf:"bytes,10,opt,name=status,proto3" json:"status,omitempty"`
	DeletedAt       string                 `protobuf:"bytes,11,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	Error           string                 `protobuf:"bytes,12,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SecretAction) Reset() {
	*x = SecretAction{}
	mi := &file_pkg_proto_plan_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretAction) ProtoMessage() {}

func (x *SecretAction) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_plan_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretAction.ProtoReflect.Descriptor instead.
func (*SecretAction) Descriptor() ([]byte, []int) {
	return file_pkg_proto_plan_proto_rawDescGZIP(), []int{2}
}

func (x *SecretAction) GetNamespacePath() string {
	if x != nil {
		return x.NamespacePath
	}
	return ""
}

func (x *SecretAction) GetMountPath() string {
	if x != nil {
		return x.MountPath
	}
	return ""
}

func (x *SecretAction) GetMountAccessor() string {
	if x != nil {
		return x.MountAccessor
	}
	return ""
}

func (x *SecretAction) GetSecretPath() string {
	if x != nil {
		return x.SecretPath
	}
	return ""
}

func (x *SecretAction) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *SecretAction) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *SecretAction) GetLastAccessed() string {
	if x != nil {
		return x.LastAccessed
	}
	return ""
}

func (x *SecretAction) GetDaysSinceAccess() int32 {
	if x != nil {
		return x.DaysSinceAccess
	}
	return 0
}

func (x *SecretAction) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SecretAction) GetDeletedAt() string {
	if x != nil {
		return x.DeletedAt
	}
	return ""
}

func (x *SecretAction) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// PlanStats contains summary statistics.
type PlanStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalSecrets  int32                  `protobuf:"varint,1,opt,name=total_secrets,json=totalSecrets,proto3" json:"total_secrets,omitempty"`
	StaleCount    int32                  `protobuf:"varint,2,opt,name=stale_count,json=staleCount,proto3" json:"stale_count,omitempty"`
	UnknownCount  int32                  `protobuf:"varint,3,opt,name=unknown_count,json=unknownCount,proto3" json:"unknown_count,omitempty"`
	ActiveCount   int32                  `protobuf:"varint,4,opt,name=active_count,json=activeCount,proto3" json:"active_count,omitempty"`
	ExcludedCount int32                  `protobuf:"varint,5,opt,name=excluded_count,json=excludedCount,proto3" json:"excluded_count,omitempty"`
	ToDeleteCount int32                  `protobuf:"varint,6,opt,name=to_delete_count,json=toDeleteCount,proto3" json:"to_delete_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlanStats) Reset() {
	*x = PlanStats{}
	mi := &file_pkg_proto_plan_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanStats) ProtoMessage() {}

func (x *PlanStats) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_plan_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanStats.ProtoReflect.Descriptor instead.
func (*PlanStats) Descriptor() ([]byte, []int) {
	return file_pkg_proto_plan_proto_rawDescGZIP(), []int{3}
}

func (x *PlanStats) GetTotalSecrets() int32 {
	if x != nil {
		return x.TotalSecrets
	}
	return 0
}

func (x *PlanStats) GetStaleCount() int32 {
	if x != nil {
		return x.StaleCount
	}
	return 0
}

func (x *PlanStats) GetUnknownCount() int32 {
	if x != nil {
		return x.UnknownCount
	}
	return 0
}

func (x *PlanStats) GetActiveCount() int32 {
	if x != nil {
		return x.ActiveCount
	}
	return 0
}

func (x *PlanStats) GetExcludedCount() int32 {
	if x != nil {
		return x.ExcludedCount
	}
	return 0
}

func (x *PlanStats) GetToDeleteCount() int32 {
	if x != nil {
		return x.ToDeleteCount
	}
	return 0
}

var File_pkg_proto_plan_proto protoreflect.FileDescriptor

const file_pkg_proto_plan_proto_rawDesc = "" +
	"\n" +
	"\x14pkg/proto/plan.proto\x12\x05proto\"\xf7\x01\n" +
	"\fDeletionPlan\x12\x1d\n" +
	"\n" +
	"created_at\x18\x01 \x01(\tR\tcreatedAt\x12%\n" +
	"\x0einventory_file\x18\x02 \x01(\tR\rinventoryFile\x12\x1f\n" +
	"\vaccess_file\x18\x03 \x01(\tR\n" +
	"accessFile\x12)\n" +
	"\x06config\x18\x04 \x01(\v2\x11.proto.PlanConfigR\x06config\x12-\n" +
	"\aactions\x18\x05 \x03(\v2\x13.proto.SecretActionR\aactions\x12&\n" +
	"\x05stats\x18\x06 \x01(\v2\x10.proto.PlanStatsR\x05stats\"\xbc\x01\n" +
	"\n" +
	"PlanConfig\x12)\n" +
	"\x10staleness_period\x18\x01 \x01(\tR\x0fstalenessPeriod\x12+\n" +
	"\x11matching_strategy\x18\x02 \x01(\tR\x10matchingStrategy\x12'\n" +
	"\x0finclude_unknown\x18\x03 \x01(\bR\x0eincludeUnknown\x12-\n" +
	"\x12exclusion_patterns\x18\x04 \x03(\tR\x11exclusionPatterns\"\xee\x02\n" +
	"\fSecretAction\x12%\n" +
	"\x0enamespace_path\x18\x01 \x01(\tR\rnamespacePath\x12\x1d\n" +
	"\n" +
	"mount_path\x18\x03 \x01(\tR\tmountPath\x12%\n" +
	"\x0emount_accessor\x18\x04 \x01(\tR\rmountAccessor\x12\x1f\n" +
	"\vsecret_path\x18\x05 \x01(\tR\n" +
	"secretPath\x12\x1a\n" +
	"\bcategory\x18\x06 \x01(\tR\bcategory\x12\x16\n" +
	"\x06reason\x18\a \x01(\tR\x06reason\x12#\n" +
	"\rlast_accessed\x18\b \x01(\tR\flastAccessed\x12*\n" +
	"\x11days_since_access\x18\t \x01(\x05R\x0fdaysSinceAccess\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"deleted_at\x18\v \x01(\tR\tdeletedAt\x12\x14\n" +
	"\x05error\x18\f \x01(\tR\x05error\"\xe8\x01\n" +
	"\tPlanStats\x12#\n" +
	"\rtotal_secrets\x18\x01 \x01(\x05R\ftotalSecrets\x12\x1f\n" +
	"\vstale_count\x18\x02 \x01(\x05R\n" +
	"staleCount\x12#\n" +
	"\runknown_count\x18\x03 \x01(\x05R\funknownCount\x12!\n" +
	"\factive_count\x18\x04 \x01(\x05R\vactiveCount\x12%\n" +
	"\x0eexcluded_count\x18\x05 \x01(\x05R\rexcludedCount\x12&\n" +
	"\x0fto_delete_count\x18\x06 \x01(\x05R\rtoDeleteCountB7Z5github.com/gsantos-hc/vault-secrets-cleanup/pkg/protob\x06proto3"

var (
	file_pkg_proto_plan_proto_rawDescOnce sync.Once
	file_pkg_proto_plan_proto_rawDescData []byte
)

func file_pkg_proto_plan_proto_rawDescGZIP() []byte {
	file_pkg_proto_plan_proto_rawDescOnce.Do(func() {
		file_pkg_proto_plan_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_plan_proto_rawDesc), len(file_pkg_proto_plan_proto_rawDesc)))
	})
	return file_pkg_proto_plan_proto_rawDescData
}

var file_pkg_proto_plan_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pkg_proto_plan_proto_goTypes = []any{
	(*DeletionPlan)(nil), // 0: proto.DeletionPlan
	(*PlanConfig)(nil),   // 1: proto.PlanConfig
	(*SecretAction)(nil), // 2: proto.SecretAction
	(*PlanStats)(nil),    // 3: proto.PlanStats
}
var file_pkg_proto_plan_proto_depIdxs = []int32{
	1, // 0: proto.DeletionPlan.config:type_name -> proto.PlanConfig
	2, // 1: proto.DeletionPlan.actions:type_name -> proto.SecretAction
	3, // 2: proto.DeletionPlan.stats:type_name -> proto.PlanStats
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pkg_proto_plan_proto_init() }
func file_pkg_proto_plan_proto_init() {
	if File_pkg_proto_plan_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_plan_proto_rawDesc), len(file_pkg_proto_plan_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_proto_plan_proto_goTypes,
		DependencyIndexes: file_pkg_proto_plan_proto_depIdxs,
		MessageInfos:      file_pkg_proto_plan_proto_msgTypes,
	}.Build()
	File_pkg_proto_plan_proto = out.File
	file_pkg_proto_plan_proto_goTypes = nil
	file_pkg_proto_plan_proto_depIdxs = nil
}
